spring:
  application:
    name: server
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/db
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
  jwt:
    secret: ${SPRING_JWT_SECRET}
    expiration: 3600000